#!/usr/bin/env python3
"""Regenerate references/image-catalog.md from assets/image-map.json.

Ported from buildImageSelectionMessages() in server.js: one line per unique
image file, keyed by the first keyword that points at it, with its description
and up to 3 aliases.

Usage: python3 scripts/build_catalog.py [--check]
  --check  only verify that every image file referenced by the map exists
"""

import json
import sys
import zipfile
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
MAP_PATH = SKILL_DIR / "assets" / "image-map.json"
IMAGES_ZIP = SKILL_DIR / "assets" / "images.zip"
CATALOG_PATH = SKILL_DIR / "references" / "image-catalog.md"


def load_map():
    with open(MAP_PATH, encoding="utf-8") as f:
        data = json.load(f)
    # Skip _meta, _attribution and any entry without a file
    return {k: v for k, v in data.items()
            if not k.startswith("_") and isinstance(v, dict) and v.get("file")}


def build_lines(image_map):
    keywords_by_file = {}
    for kw, img in image_map.items():
        keywords_by_file.setdefault(img["file"], []).append(kw)

    lines = []
    for kws in keywords_by_file.values():
        img = image_map[kws[0]]
        desc = img.get("desc") or img.get("alt") or kws[0]
        aliases = ", ".join(kws[1:4])
        lines.append(f'"{kws[0]}": {desc}' + (f" — also: {aliases}" if aliases else ""))
    return lines


def missing_files(image_map):
    with zipfile.ZipFile(IMAGES_ZIP) as zf:
        packed = set(zf.namelist())
    return sorted({img["file"] for img in image_map.values() if img["file"] not in packed})


def main():
    image_map = load_map()
    missing = missing_files(image_map)
    if missing:
        print(f"ERROR: {len(missing)} image file(s) referenced in the map do not exist:")
        for f in missing:
            print(f"  {f}")
        sys.exit(1)

    if "--check" in sys.argv:
        print(f"OK: all {len(image_map)} keywords resolve to existing files.")
        return

    lines = build_lines(image_map)
    header = (
        "# Image catalog\n\n"
        "Generated by `scripts/build_catalog.py` from `assets/image-map.json`. Do not edit by hand.\n\n"
        "One line per image: `\"keyword\": description — also: aliases`. "
        "Use only the quoted keyword (or an alias) as `imageKeyword`.\n\n"
    )
    CATALOG_PATH.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines)} images ({len(image_map)} keywords) to {CATALOG_PATH.relative_to(SKILL_DIR)}")


if __name__ == "__main__":
    main()
